'use strict';

let genUser = (function() {
  let iUserIdCounter = 1;
  return function() {
    return {
      id: iUserIdCounter,
      name: 'User' + iUserIdCounter++,
      colour: 'e0e3e8',
    };
  };
})();

// Chat history
let aHistory = [];
let createRecord = (function() {
  let iRecordIdCounter = 1;
  return function(user, msg) {
    let record = { 
      id: iRecordIdCounter++,
      time: Date.now(),
      user: user, 
      msg: msg,
    };
    // Only keep 200 messages
    while (aHistory.length >= 200) {
      aHistory.shift(); // pop fist array element
    }
    aHistory.push(record); // push onto end of array
    return record;
  };
})();
// Update user information for historic messages
//   Could have updated nickname or colour
let changeHistoricUser = function (user) {
  for (let record of aHistory) {
    if (record.user.id === user.id) record.user = user;
  }
};

// Users of the system
let oUsers = {};
// Online Users as a list of user id's
let aOnlineUsers = [];
let userSetOnline = function(user) {
  for (let iOnlineUserId of aOnlineUsers) {
    if (iOnlineUserId === user.id) return;
  }
  aOnlineUsers.push(user.id);
};
let userSetOffline = function(user) {
  let i = aOnlineUsers.indexOf(user.id);
  if (i >= 0) aOnlineUsers.splice(i, 1);
};
let getOnlineUsers = function() {
  let oOnlineUsers = {};
  for (let iOnlineUserId of aOnlineUsers) {
    oOnlineUsers[iOnlineUserId] = oUsers[iOnlineUserId];
  }
  return oOnlineUsers;
};

let init = function(io) {
  io.on('connection', function(socket){
    // If this user has never connected before, no session.user will exist
    if (!socket.request.session.user) {
      let oNewUser = genUser();
      oUsers[oNewUser.id] = oNewUser;
      socket.request.session.user = oNewUser;
      socket.request.session.save();
    }
    // Set this user to be online
    userSetOnline(socket.request.session.user);
    // Tell client their user info and send history and list of online users
    socket.emit('hello', { 
      you: socket.request.session.user,
      users: getOnlineUsers(),
      history: aHistory,
    });
    // Then tell everyone else that someone else has joined
    socket.broadcast.emit('user join', socket.request.session.user);

    // When User Leaves set them offline and tell everyone they left
    socket.on('disconnect', function () {
      userSetOffline(socket.request.session.user);
      socket.broadcast.emit('user leave', socket.request.session.user);
    });

    // User Sends Message, add to history and broadcast to every user
    socket.on('new message', function(msg){
      io.emit('new message', createRecord(socket.request.session.user, msg));
    });

    // User Changes Name
    socket.on('change name', function(sNewName) {
      sNewName = sNewName.trim(); // remove leading and trailing whitespace
      if (socket.request.session.user.name === sNewName)
        return socket.emit('change name', { success: false, msg: 'That is your current username' });
      if (sNewName === '')
        return socket.emit('change name', { success: false, msg: 'Usernames must contain visible characters' });
      if (/^User[0-9]*$/g.test(sNewName)) // User[0-9]* usernames reserved to avoid conflict with autogenerated names
        return socket.emit('change name', { success: false, msg: 'That username is reserved, please pick another one' });
      for (let iUserId of Object.keys(oUsers)) { // Force nicknames to be unique
        if (oUsers[iUserId].name === sNewName)
          return socket.emit('change name', { success: false, msg: 'That username is already taken, please pick another one' });
      }
      // Update user inforation on server and on all clients
      oUsers[socket.request.session.user.id].name = sNewName;
      socket.request.session.user.name = sNewName;
      socket.request.session.save();
      changeHistoricUser(socket.request.session.user);
      socket.broadcast.emit('user change name', socket.request.session.user);
      socket.emit('change name', { success: true, user: socket.request.session.user });
    });

    // User Changes Colour
    socket.on('change colour', function(sNewColour) {
      sNewColour = sNewColour.toLowerCase().trim(); // remove leading and trailing whitespace
      if (sNewColour.length !== 6)
        return socket.emit('change colour', { success: false, msg: 'Colours must be 6 characters long' });
      if (/[^0-9a-f]/g.test(sNewColour))
        return socket.emit('change colour', { success: false, msg: 'Colours can only contain the characters 0-9, A-F, or a-f' });
      // Update user information on server and on all clients
      oUsers[socket.request.session.user.id].colour = sNewColour;
      socket.request.session.user.colour = sNewColour;
      socket.request.session.save();
      changeHistoricUser(socket.request.session.user);
      socket.broadcast.emit('user change colour', socket.request.session.user );
      socket.emit('change colour', { success: true, user: socket.request.session.user });
    });
  });
};

module.exports = init;
